config/routes.rb
Rails.application.routes.draw do
  post '/songwritings' => 'songwritings#create'
  get '/songwritings/:id' => 'category#songwriting_info', as: "songwriting"
  get '/songwritings/:id/edit' => 'songwritings#edit', as: "edit_songwriting"
  patch '/songwritings/:id' => 'songwritings#update'
  delete '/songwritings/:id' => 'songwritings#destroy'
  
  post '/covers' => 'covers#create'
  get '/covers/:id' => 'category#cover_info', as: "cover"
  get '/covers/:id/edit' => 'covers#edit', as: "edit_cover"
  patch '/covers/:id' => 'covers#update'
  delete '/covers/:id' => 'covers#destroy'
  
  post '/shows' => 'shows#create'
  get '/shows/:id' => 'category#show_info', as: "show"
  get '/shows/:id/edit' => 'shows#edit', as: "edit_show"
  patch '/shows/:id' => 'shows#update'
  delete '/shows/:id' => 'shows#destroy'
  
  root 'home#index'
  get '/' => 'home#index'
  get 'home/index'
  get 'home/result'
  get 'home/upload'

  get 'category/songwriting/:genre' => 'category#songwriting'
  get 'category/cover'
  get 'category/show'
  get 'category/songwriting_view/:id' => 'category#songwriting_view'

  get 'category/songwriting_info'
  

  get 'muserchart/index' => 'muserchart#index'
  get 'muserchart/cover' => 'muserchart#cover'
  get 'muserchart/show' => 'muserchart#show'
  
  get 'history/index'
  get 'history/myspace'
  get 'history/mymuser'
  get 'history/myheart'
  get 'mymuser/index'
  get 'mymusic/index'
  

  devise_for :users
  get 'new/index'

  get '/like/:id' => 'category#like'
  get '/like_cancel/:id' => 'category#like_cancel'
  
  get '/like2/:id' => 'category#like2'
  get '/like2_cancel/:id' => 'category#like2_cancel'
  
  get '/like3/:id' => 'category#like3'
  get '/like3_cancel/:id' => 'category#like3_cancel'
  
  
  
  
  post 'category/sw_comment_create/:songwriting_id' => 'category#sw_comment_create'
  post 'category/c_comment_create/:cover_id' => 'category#c_comment_create'
  post 'category/s_comment_create/:show_id' => 'category#s_comment_create'
  
  get 'category/sw_comment_destroy/:songwriting_id' => 'category#sw_comment_destroy'
  get 'category/c_comment_destroy/:cover_id' => 'category#c_comment_destroy'
  get 'category/s_comment_destroy/:show_id' => 'category#s_comment_destroy'
  
  

end

app/models/c_comment.rb
class CComment < ActiveRecord::Base
    belongs_to :user
    belongs_to :cover

end

app/models/cover.rb
class Cover < ActiveRecord::Base
    has_many :like2s
    belongs_to :user
    has_many :c_comments

    has_many :impressions, :as=>:impressionable
      is_impressionable :counter_cache => true, :column_name => :hits
    def impression_count
        impressions.size
    end
     
    def unique_impression_count
        # impressions.group(:ip_address).size gives => {'127.0.0.1'=>9, '0.0.0.0'=>1}
        # so getting keys from the hash and calculating the number of keys
        impressions.group(:ip_address).size.keys.length #TESTED
    end

end

app/models/like.rb
class Like < ActiveRecord::Base
    
    belongs_to :Songwriting, :counter_cache => :likes_count
    belongs_to :user


end

app/models/like2.rb
class Like2 < ActiveRecord::Base
    belongs_to :cover
    belongs_to :user


end

app/models/like3.rb
class Like3 < ActiveRecord::Base
    belongs_to :show
    belongs_to :user

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
    belongs_to :post
end

app/models/s_comment.rb
class SComment < ActiveRecord::Base
    belongs_to :user
    belongs_to :show


end

app/models/show.rb
class Show < ActiveRecord::Base
    has_many :like3s
    belongs_to :user
    has_many :s_comments
    has_many :impressions, :as=>:impressionable
      is_impressionable :counter_cache => true, :column_name => :hits
    def impression_count
        impressions.size
    end
     
    def unique_impression_count
        # impressions.group(:ip_address).size gives => {'127.0.0.1'=>9, '0.0.0.0'=>1}
        # so getting keys from the hash and calculating the number of keys
        impressions.group(:ip_address).size.keys.length #TESTED
    end


end

app/models/songwriting.rb
class Songwriting < ActiveRecord::Base
  has_many :playlists
  has_many :likes
  belongs_to :user
  has_many :sw_comments
    has_many :impressions, :as=>:impressionable
     is_impressionable :counter_cache => true, :column_name => :hits
    def impression_count
        impressions.size
    end
     
    def unique_impression_count
        # impressions.group(:ip_address).size gives => {'127.0.0.1'=>9, '0.0.0.0'=>1}
        # so getting keys from the hash and calculating the number of keys
        impressions.group(:ip_address).size.keys.length #TESTED
    end
    
    


end

app/models/sw_comment.rb
class SwComment < ActiveRecord::Base
    belongs_to :user
    belongs_to :songwriting
   
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  mount_uploader :avatar, AvatarUploader

  has_many :likes
  has_many :like2s
  has_many :like3s
  has_many :songwritings
  has_many :covers
  has_many :shows
  
  def like?(x)
    Like.find_by(user_id: self.id, songwriting_id: x.id).present?
  end 
  
  def like2?(x)
    Like2.find_by(user_id: self.id, cover_id: x.id).present?
  end
  
  def like3?(x)
    Like3.find_by(user_id: self.id, show_id: x.id).present?
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @songwriting1 = Songwriting.order('created_at DESC').first(4)
    @songwriting2 = Songwriting.order('created_at DESC').limit(4).offset(4)
    @songwriting3 = Songwriting.order('created_at DESC').limit(4).offset(8)
    @cover1 = Cover.order('created_at DESC').first(3)
    @cover2 = Cover.order('created_at DESC').limit(3).offset(3)
    @cover3 = Cover.order('created_at DESC').limit(3).offset(6)
    @show1 = Show.order('created_at DESC').first(3)
    @show2 = Show.order('created_at DESC').limit(3).offset(3)
    @show3 = Show.order('created_at DESC').limit(3).offset(6)
    
    @songwriting = Songwriting.all
    @sw_chart = @songwriting.order('hits DESC').take(10)
    
    @show = Show.all
    @s_chart = @show.order('hits DESC').take(4)
  end
  
  def upload
    @songwriting = Songwriting.new
    @cover = Cover.new
    @show = Show.new
    
  end
  def result
    @query = params[:query]
    if params[:query].nil?
      @songwriting = Songwriting.all
      @cover = Cover.all
      @show = Show.all
    else
      @songwriting = Songwriting.where("title LIKE ?", "%#{params[:query]}%")
      @cover = Cover.where("title LIKE ?", "%#{params[:query]}%")
      @show = Show.where("title LIKE ?", "%#{params[:query]}%")
    end
  end
  
end

  # private

  # def search(&block)    
  #   if params[:q]
  #     @results = yield if block_given?

  #     respond_to do |format|
  #       format.html # resources.html.erb
  #       format.json { render json: @results }
  #     end
  #   else
  #     redirect_to root_url, :notice => 'No search query was specified.'
  #   end
  # end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/covers_helper.rb
module CoversHelper
end

app/helpers/history_helper.rb
module HistoryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/muserchart_helper.rb
module MuserchartHelper
end

app/helpers/mymuser_helper.rb
module MymuserHelper
end

app/helpers/mymusic_helper.rb
module MymusicHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/home/result.html.erb
<div class="row history-row first_row">
    <div class="history-profile-wrap result-wrap">
        <h1><i class="fa fa-search" aria-hidden="true"></i>&nbsp;"<span><%=@query%></span>" 검색 결과</h1>
    </div>
</div>

<div class="row row_style">
 <div class="row-header">
    <h1 class="page-header header_style">
        창작
    </h1>
 </div>
</div>

<div class="row history-row">
    <div class="history-profile-wrap">
        
        <div class="tab-content new-music-content">
            <div role="tabpanel" class="tab-pane active" id="create">
                <div class="row list">
                  <% @songwriting.each do |s| %>
                    <div class="col-6 col-md-4 col-lg-3">
                      <div class="list-wrap">
                        <div class="thumbnail">
                          <a href="javascript:popupOpen(<%=s.id%>);">
                            <div class="list-img-wrap">
                              <% unless s.album_pic.nil? %>
                                <img src="<%= s.album_pic %>" width="170" height="170" alt="앨범이미지">
                              <% else %>
                                <img src="http://via.placeholder.com/170x170" width="170" height="170" alt="앨범이미지">
                              <% end %>
                                <div>
                                    <i class="fa fa-music fa-2x play-icon" aria-hidden="true"></i>
                                </div>
                            </div>
                          </a>
                          <div class="caption">
                            <p>
                            <% if user_signed_in? %>
                              <%= link_to "#{s.title}", songwriting_path(s.id), class: "list-title" %>
                            <% else %>
                              <a href="javascript:alert('로그인을 해주세요');" class="list-title"><%=s.title%></a>
                            <% end %>
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>
                  <% end %>
               </div>
            </div>
        </div>
        
    </div>
</div>

<!--My Muser-->
<div class="row row_style">
 <div class="row-header">
    <h1 class="page-header header_style">
        커버
    </h1>
 </div>
</div>

<div class="row history-row">
    <div class="history-profile-wrap">
        <div class="tab-content new-music-content">
            <div role="tabpanel" class="tab-pane active" id="like_cover">
                <div class="row list">
                  <% @cover.each do |c| %>
                    <div class="col-6 col-md-6 col-lg-4">
                      <div class="list-wrap show-list-wrap">
                          <div class="thumbnail">
                              <div class="list-show">
                                <ul class="list-unstyled video-list-thumbs row">
                                	<li class="col-12">
                                		<a href="<%=cover_path(c.id)%>" title="Claudio Bravo, antes su debut con el Barça en la Liga">
                                		<% unless c.cover_pic.nil? %>
                                      <img src="<%= c.cover_pic %>" width="280" height="160" alt="앨범이미지">
                                    <% else %>
                                      <img src="http://via.placeholder.com/280X160" width="280" height="160">
                                    <% end %>
                                			<span class="glyphicon glyphicon-play"></span>
                                			<span class="duration">03:15</span>
                                		</a>
                                	</li>
                                </ul>
                              </div>
                            <div class="caption">
                              <p>
                              <% if user_signed_in? %>
                                <%= link_to "#{c.title}", cover_path(c.id), class: "list-title" %>
                              <% elsif %>
                                <a href="javascript:alert('로그인을 해주세요');" class="list-title"><%=s.title%></a>
                              <% end %>
                              </p>
                            </div>
                          </div> 
                        </div>
                      </div>
                    <!--</div>-->
                  <% end %>
               </div>
            </div>
        </div>
    </div>
</div>

<!--my favorite-->
<div class="row row_style">
 <div class="row-header">
    <h1 class="page-header header_style">
        공연
    </h1>
 </div>
</div>

<div class="row history-row">
    <div class="history-profile-wrap">
        
        <div class="tab-content new-music-content">
            <div role="tabpanel" class="tab-pane active" id="like_cover">
                <div class="row list">
                  <% @show.each do |s| %>
                    <div class="col-6 col-md-6 col-lg-4">
                      <div class="list-wrap show-list-wrap">
                          <div class="thumbnail">
                              <div class="list-show">
                                <ul class="list-unstyled video-list-thumbs row">
                                	<li class="col-12">
                                		<a href="" title="Claudio Bravo, antes su debut con el Barça en la Liga">
                                    <% unless s.show_pic.nil? %>
                                      <img src="<%= s.show_pic %>" width="280" height="160" alt="앨범이미지">
                                    <% else %>
                                      <img src="http://via.placeholder.com/280X160" width="280" height="160">
                                    <% end %>
                                			<span class="glyphicon glyphicon-play"></span>
                                			<span class="duration">03:15</span>
                                		</a>
                                	</li>
                                </ul>
                              </div>
                            <div class="caption">
                              <p>
                              <% if user_signed_in? %>
                                <%= link_to "#{s.title}", cover_path(s.id), class: "list-title" %>
                              <% elsif %>
                                <a href="javascript:alert('로그인을 해주세요');" class="list-title"><%=s.title%></a>
                              <% end %>
                              </p>
                            </div>
                          </div> 
                        </div>
                      </div>
                    <!--</div>-->
                  <% end %>
               </div>
            </div>
        </div>
        
    </div>
</div>

app/views/home/upload.html.erb
<div class="row first_row row_style">
    <div class="row-header">
        <h1 class="page-header header_style">
            업로드
        </h1>
        <div role="tabpanel">
        
          <!-- Nav tabs -->
          <ul class="nav nav-tabs nav-tabs_style" role="tablist">
            <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">창작</a></li>
            <li role="presentation"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab">커버</a></li>
            <li role="presentation"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">공연</a></li>
          </ul>

        </div>
    </div>
    <!-- Tab panes -->
      <div class="tab-content new-music-content">
        
        <div role="tabpanel" class="tab-pane active" id="home">
            <div class="row div_devise">
              <div>
                <h2>창작 업로드</h2>
                <div>
                <%= form_for @songwriting, multipart: true do |f| %> 
                <input type="hidden" name="user_id" value="<%= current_user.id %>">
                <input type="hidden" name="user_email" value="<%= current_user.email %>">
                <input type="hidden" name="user_name" value="<%= current_user.name %>">
                  
                  <div class="field field_style">
                    <%= f.label :album_pic %><br />
                    <%= f.file_field :album_pic, accept: "image/*" %>
                  </div>
                  <div class="field field_style">
                    <%= f.label :music %><br />
                    <%= f.file_field :music, accept: "audio/*" %>
                  </div>
                  <div class="field field_style">
                    <%= f.label :name %><br />
                    <%= f.text_field :title %>
                  </div>
                  <div class="field field_style">
                    <%= f.label :genre %><br />
                    <%= f.select(:genre, options_for_select([["발라드/댄스/팝"], ["힙합/알앤비"], ["일렉트로닉"], ["락/메탈"], ["재즈"], ["인디"]])) %>
                  </div>
                  <div class="field field_style">
                    <%= f.label :content %><br />
                    <%= f.text_area :content %>
                  </div>

                  <div class="field field_style">
                    <%= f.label :lyrics %><br />
                    <%= f.text_area :lyrics %>
                  </div>
                  <div class="actions field_style">
                    <%= f.submit "Upload" %>
                  </div>
                <% end %>
                </div>
              </div>
            </div>            
        </div>
        
        <div role="tabpanel" class="tab-pane" id="profile">
            <div class="row div_devise">
              <div>
                <h2>커버 업로드</h2>
                <div>
                <%= form_for @cover, multipart: true do |f| %>
                <input type="hidden" name="user_id" value="<%= current_user.id %>">
                <input type="hidden" name="user_email" value="<%= current_user.email %>">
                <input type="hidden" name="user_name" value="<%= current_user.name %>">
                  <div class="field field_style">
                    <%= f.label :cover_pic%><br />
                    <%= f.file_field :cover_pic, accept: "image/*"  %>
                  </div>
                  <div class="field field_style">
                    <%= f.label :cover_mic%><br />
                    <%= f.file_field :cover_mic, accept: "video/*"  %>
                  </div>
                  <div class="field field_style">
                    <%= f.label :name %><br />
                    <%= f.text_field :title %>
                  </div>
                  <div class="field field_style">
                    <%= f.label :original %><br />
                    <%= f.text_field :original %>
                  </div>
                  <div class="field field_style">
                    <%= f.label :content %><br />
                    <%= f.text_area :content %>
                  </div>

                  <div class="field field_style">
                    <%= f.label :lyrics %><br />
                    <%= f.text_area :lyrics %>
                  </div>
                  <div class="actions field_style">
                    <%= f.submit "Upload" %>
                  </div>
                <% end %>
                </div>
              </div>
            </div>                 
        </div>
        
        <div role="tabpanel" class="tab-pane" id="messages">
            <div class="row div_devise">
              <div>
                <h2>공연 업로드</h2>
                <div>
                <%= form_for @show, multipart: true do |f| %>
                <input type="hidden" name="user_id" value="<%= current_user.id %>">
                <input type="hidden" name="user_email" value="<%= current_user.email %>">
                <input type="hidden" name="user_name" value="<%= current_user.name %>">
                  <div class="field field_style">
                    <%= f.label :show_pic%><br />
                    <%= f.file_field :show_pic, accept: 'image/*'  %>
                  </div>
                  <div class="field field_style">
                    <%= f.label :show_mic%><br />
                    <%= f.file_field :show_mic, accept: 'video/*'  %>
                  </div>
                  <div class="field field_style">
                    <%= f.label :title %><br />
                    <%= f.text_field :title %>
                  </div>  
                  <div class="field field_style">
                    <%= f.label :teamname %><br />
                    <%= f.text_field :teamname %>
                  </div>
                  <div class="field field_style">
                    <%= f.label :content %><br />
                    <%= f.text_area :content %>
                  </div>
                  <div class="actions field_style">
                    <%= f.submit "Upload" %>
                  </div>
                <% end %>
                </div>
              </div>
            </div>                 
        </div>
        
      </div>
</div>